/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class orp_orp_PosixFile_ErrnoException */

#ifndef _Included_orp_orp_PosixFile_ErrnoException
#define _Included_orp_orp_PosixFile_ErrnoException
#ifdef __cplusplus
extern "C" {
#endif
#undef orp_orp_PosixFile_ErrnoException_serialVersionUID
#define orp_orp_PosixFile_ErrnoException_serialVersionUID -3042686055658047285LL
#undef orp_orp_PosixFile_ErrnoException_serialVersionUID
#define orp_orp_PosixFile_ErrnoException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
