// THIS FILE IS AUTOGENERATED BY wb_intercon_gen
// ANY MANUAL CHANGES WILL BE LOST
module wb_intercon
   (input         wb_clk_i,
    input         wb_rst_i,
    input  [31:0] wb_or1k_i_adr_i,
    input  [31:0] wb_or1k_i_dat_i,
    input   [3:0] wb_or1k_i_sel_i,
    input         wb_or1k_i_we_i,
    input         wb_or1k_i_cyc_i,
    input         wb_or1k_i_stb_i,
    input   [2:0] wb_or1k_i_cti_i,
    input   [1:0] wb_or1k_i_bte_i,
    output [31:0] wb_or1k_i_dat_o,
    output        wb_or1k_i_ack_o,
    output        wb_or1k_i_err_o,
    output        wb_or1k_i_rty_o,
    input  [31:0] wb_or1k_d_adr_i,
    input  [31:0] wb_or1k_d_dat_i,
    input   [3:0] wb_or1k_d_sel_i,
    input         wb_or1k_d_we_i,
    input         wb_or1k_d_cyc_i,
    input         wb_or1k_d_stb_i,
    input   [2:0] wb_or1k_d_cti_i,
    input   [1:0] wb_or1k_d_bte_i,
    output [31:0] wb_or1k_d_dat_o,
    output        wb_or1k_d_ack_o,
    output        wb_or1k_d_err_o,
    output        wb_or1k_d_rty_o,
    input  [31:0] wb_dbg_adr_i,
    input  [31:0] wb_dbg_dat_i,
    input   [3:0] wb_dbg_sel_i,
    input         wb_dbg_we_i,
    input         wb_dbg_cyc_i,
    input         wb_dbg_stb_i,
    input   [2:0] wb_dbg_cti_i,
    input   [1:0] wb_dbg_bte_i,
    output [31:0] wb_dbg_dat_o,
    output        wb_dbg_ack_o,
    output        wb_dbg_err_o,
    output        wb_dbg_rty_o,
    output [31:0] wb_rom0_adr_o,
    output [31:0] wb_rom0_dat_o,
    output  [3:0] wb_rom0_sel_o,
    output        wb_rom0_we_o,
    output        wb_rom0_cyc_o,
    output        wb_rom0_stb_o,
    output  [2:0] wb_rom0_cti_o,
    output  [1:0] wb_rom0_bte_o,
    input  [31:0] wb_rom0_dat_i,
    input         wb_rom0_ack_i,
    input         wb_rom0_err_i,
    input         wb_rom0_rty_i,
    output [31:0] wb_ram0_adr_o,
    output [31:0] wb_ram0_dat_o,
    output  [3:0] wb_ram0_sel_o,
    output        wb_ram0_we_o,
    output        wb_ram0_cyc_o,
    output        wb_ram0_stb_o,
    output  [2:0] wb_ram0_cti_o,
    output  [1:0] wb_ram0_bte_o,
    input  [31:0] wb_ram0_dat_i,
    input         wb_ram0_ack_i,
    input         wb_ram0_err_i,
    input         wb_ram0_rty_i,
    output [31:0] wb_uart0_adr_o,
    output  [7:0] wb_uart0_dat_o,
    output  [3:0] wb_uart0_sel_o,
    output        wb_uart0_we_o,
    output        wb_uart0_cyc_o,
    output        wb_uart0_stb_o,
    output  [2:0] wb_uart0_cti_o,
    output  [1:0] wb_uart0_bte_o,
    input   [7:0] wb_uart0_dat_i,
    input         wb_uart0_ack_i,
    input         wb_uart0_err_i,
    input         wb_uart0_rty_i,
    output [31:0] wb_gpio0_adr_o,
    output  [7:0] wb_gpio0_dat_o,
    output  [3:0] wb_gpio0_sel_o,
    output        wb_gpio0_we_o,
    output        wb_gpio0_cyc_o,
    output        wb_gpio0_stb_o,
    output  [2:0] wb_gpio0_cti_o,
    output  [1:0] wb_gpio0_bte_o,
    input   [7:0] wb_gpio0_dat_i,
    input         wb_gpio0_ack_i,
    input         wb_gpio0_err_i,
    input         wb_gpio0_rty_i,
    output [31:0] wb_trng_adr_o,
    output  [7:0] wb_trng_dat_o,
    output  [3:0] wb_trng_sel_o,
    output        wb_trng_we_o,
    output        wb_trng_cyc_o,
    output        wb_trng_stb_o,
    output  [2:0] wb_trng_cti_o,
    output  [1:0] wb_trng_bte_o,
    input   [7:0] wb_trng_dat_i,
    input         wb_trng_ack_i,
    input         wb_trng_err_i,
    input         wb_trng_rty_i,
    output [31:0] wb_crypto_aes_adr_o,
    output [31:0] wb_crypto_aes_dat_o,
    output  [3:0] wb_crypto_aes_sel_o,
    output        wb_crypto_aes_we_o,
    output        wb_crypto_aes_cyc_o,
    output        wb_crypto_aes_stb_o,
    output  [2:0] wb_crypto_aes_cti_o,
    output  [1:0] wb_crypto_aes_bte_o,
    input  [31:0] wb_crypto_aes_dat_i,
    input         wb_crypto_aes_ack_i,
    input         wb_crypto_aes_err_i,
    input         wb_crypto_aes_rty_i,
    output [31:0] wb_crypto_sha256_adr_o,
    output [31:0] wb_crypto_sha256_dat_o,
    output  [3:0] wb_crypto_sha256_sel_o,
    output        wb_crypto_sha256_we_o,
    output        wb_crypto_sha256_cyc_o,
    output        wb_crypto_sha256_stb_o,
    output  [2:0] wb_crypto_sha256_cti_o,
    output  [1:0] wb_crypto_sha256_bte_o,
    input  [31:0] wb_crypto_sha256_dat_i,
    input         wb_crypto_sha256_ack_i,
    input         wb_crypto_sha256_err_i,
    input         wb_crypto_sha256_rty_i,
    output [31:0] wb_fauxfs_cpu_adr_o,
    output [31:0] wb_fauxfs_cpu_dat_o,
    output  [3:0] wb_fauxfs_cpu_sel_o,
    output        wb_fauxfs_cpu_we_o,
    output        wb_fauxfs_cpu_cyc_o,
    output        wb_fauxfs_cpu_stb_o,
    output  [2:0] wb_fauxfs_cpu_cti_o,
    output  [1:0] wb_fauxfs_cpu_bte_o,
    input  [31:0] wb_fauxfs_cpu_dat_i,
    input         wb_fauxfs_cpu_ack_i,
    input         wb_fauxfs_cpu_err_i,
    input         wb_fauxfs_cpu_rty_i,
    output [31:0] wb_nand_cpu_adr_o,
    output [31:0] wb_nand_cpu_dat_o,
    output  [3:0] wb_nand_cpu_sel_o,
    output        wb_nand_cpu_we_o,
    output        wb_nand_cpu_cyc_o,
    output        wb_nand_cpu_stb_o,
    output  [2:0] wb_nand_cpu_cti_o,
    output  [1:0] wb_nand_cpu_bte_o,
    input  [31:0] wb_nand_cpu_dat_i,
    input         wb_nand_cpu_ack_i,
    input         wb_nand_cpu_err_i,
    input         wb_nand_cpu_rty_i,
    output [31:0] wb_bootrom0_adr_o,
    output [31:0] wb_bootrom0_dat_o,
    output  [3:0] wb_bootrom0_sel_o,
    output        wb_bootrom0_we_o,
    output        wb_bootrom0_cyc_o,
    output        wb_bootrom0_stb_o,
    output  [2:0] wb_bootrom0_cti_o,
    output  [1:0] wb_bootrom0_bte_o,
    input  [31:0] wb_bootrom0_dat_i,
    input         wb_bootrom0_ack_i,
    input         wb_bootrom0_err_i,
    input         wb_bootrom0_rty_i);

wire [31:0] wb_m2s_or1k_i_rom0_adr;
wire [31:0] wb_m2s_or1k_i_rom0_dat;
wire  [3:0] wb_m2s_or1k_i_rom0_sel;
wire        wb_m2s_or1k_i_rom0_we;
wire        wb_m2s_or1k_i_rom0_cyc;
wire        wb_m2s_or1k_i_rom0_stb;
wire  [2:0] wb_m2s_or1k_i_rom0_cti;
wire  [1:0] wb_m2s_or1k_i_rom0_bte;
wire [31:0] wb_s2m_or1k_i_rom0_dat;
wire        wb_s2m_or1k_i_rom0_ack;
wire        wb_s2m_or1k_i_rom0_err;
wire        wb_s2m_or1k_i_rom0_rty;
wire [31:0] wb_m2s_or1k_i_bootrom0_adr;
wire [31:0] wb_m2s_or1k_i_bootrom0_dat;
wire  [3:0] wb_m2s_or1k_i_bootrom0_sel;
wire        wb_m2s_or1k_i_bootrom0_we;
wire        wb_m2s_or1k_i_bootrom0_cyc;
wire        wb_m2s_or1k_i_bootrom0_stb;
wire  [2:0] wb_m2s_or1k_i_bootrom0_cti;
wire  [1:0] wb_m2s_or1k_i_bootrom0_bte;
wire [31:0] wb_s2m_or1k_i_bootrom0_dat;
wire        wb_s2m_or1k_i_bootrom0_ack;
wire        wb_s2m_or1k_i_bootrom0_err;
wire        wb_s2m_or1k_i_bootrom0_rty;
wire [31:0] wb_m2s_or1k_d_rom0_adr;
wire [31:0] wb_m2s_or1k_d_rom0_dat;
wire  [3:0] wb_m2s_or1k_d_rom0_sel;
wire        wb_m2s_or1k_d_rom0_we;
wire        wb_m2s_or1k_d_rom0_cyc;
wire        wb_m2s_or1k_d_rom0_stb;
wire  [2:0] wb_m2s_or1k_d_rom0_cti;
wire  [1:0] wb_m2s_or1k_d_rom0_bte;
wire [31:0] wb_s2m_or1k_d_rom0_dat;
wire        wb_s2m_or1k_d_rom0_ack;
wire        wb_s2m_or1k_d_rom0_err;
wire        wb_s2m_or1k_d_rom0_rty;
wire [31:0] wb_m2s_or1k_d_ram0_adr;
wire [31:0] wb_m2s_or1k_d_ram0_dat;
wire  [3:0] wb_m2s_or1k_d_ram0_sel;
wire        wb_m2s_or1k_d_ram0_we;
wire        wb_m2s_or1k_d_ram0_cyc;
wire        wb_m2s_or1k_d_ram0_stb;
wire  [2:0] wb_m2s_or1k_d_ram0_cti;
wire  [1:0] wb_m2s_or1k_d_ram0_bte;
wire [31:0] wb_s2m_or1k_d_ram0_dat;
wire        wb_s2m_or1k_d_ram0_ack;
wire        wb_s2m_or1k_d_ram0_err;
wire        wb_s2m_or1k_d_ram0_rty;
wire [31:0] wb_m2s_or1k_d_uart0_adr;
wire [31:0] wb_m2s_or1k_d_uart0_dat;
wire  [3:0] wb_m2s_or1k_d_uart0_sel;
wire        wb_m2s_or1k_d_uart0_we;
wire        wb_m2s_or1k_d_uart0_cyc;
wire        wb_m2s_or1k_d_uart0_stb;
wire  [2:0] wb_m2s_or1k_d_uart0_cti;
wire  [1:0] wb_m2s_or1k_d_uart0_bte;
wire [31:0] wb_s2m_or1k_d_uart0_dat;
wire        wb_s2m_or1k_d_uart0_ack;
wire        wb_s2m_or1k_d_uart0_err;
wire        wb_s2m_or1k_d_uart0_rty;
wire [31:0] wb_m2s_or1k_d_gpio0_adr;
wire [31:0] wb_m2s_or1k_d_gpio0_dat;
wire  [3:0] wb_m2s_or1k_d_gpio0_sel;
wire        wb_m2s_or1k_d_gpio0_we;
wire        wb_m2s_or1k_d_gpio0_cyc;
wire        wb_m2s_or1k_d_gpio0_stb;
wire  [2:0] wb_m2s_or1k_d_gpio0_cti;
wire  [1:0] wb_m2s_or1k_d_gpio0_bte;
wire [31:0] wb_s2m_or1k_d_gpio0_dat;
wire        wb_s2m_or1k_d_gpio0_ack;
wire        wb_s2m_or1k_d_gpio0_err;
wire        wb_s2m_or1k_d_gpio0_rty;
wire [31:0] wb_m2s_or1k_d_trng_adr;
wire [31:0] wb_m2s_or1k_d_trng_dat;
wire  [3:0] wb_m2s_or1k_d_trng_sel;
wire        wb_m2s_or1k_d_trng_we;
wire        wb_m2s_or1k_d_trng_cyc;
wire        wb_m2s_or1k_d_trng_stb;
wire  [2:0] wb_m2s_or1k_d_trng_cti;
wire  [1:0] wb_m2s_or1k_d_trng_bte;
wire [31:0] wb_s2m_or1k_d_trng_dat;
wire        wb_s2m_or1k_d_trng_ack;
wire        wb_s2m_or1k_d_trng_err;
wire        wb_s2m_or1k_d_trng_rty;
wire [31:0] wb_m2s_or1k_d_crypto_aes_adr;
wire [31:0] wb_m2s_or1k_d_crypto_aes_dat;
wire  [3:0] wb_m2s_or1k_d_crypto_aes_sel;
wire        wb_m2s_or1k_d_crypto_aes_we;
wire        wb_m2s_or1k_d_crypto_aes_cyc;
wire        wb_m2s_or1k_d_crypto_aes_stb;
wire  [2:0] wb_m2s_or1k_d_crypto_aes_cti;
wire  [1:0] wb_m2s_or1k_d_crypto_aes_bte;
wire [31:0] wb_s2m_or1k_d_crypto_aes_dat;
wire        wb_s2m_or1k_d_crypto_aes_ack;
wire        wb_s2m_or1k_d_crypto_aes_err;
wire        wb_s2m_or1k_d_crypto_aes_rty;
wire [31:0] wb_m2s_or1k_d_crypto_sha256_adr;
wire [31:0] wb_m2s_or1k_d_crypto_sha256_dat;
wire  [3:0] wb_m2s_or1k_d_crypto_sha256_sel;
wire        wb_m2s_or1k_d_crypto_sha256_we;
wire        wb_m2s_or1k_d_crypto_sha256_cyc;
wire        wb_m2s_or1k_d_crypto_sha256_stb;
wire  [2:0] wb_m2s_or1k_d_crypto_sha256_cti;
wire  [1:0] wb_m2s_or1k_d_crypto_sha256_bte;
wire [31:0] wb_s2m_or1k_d_crypto_sha256_dat;
wire        wb_s2m_or1k_d_crypto_sha256_ack;
wire        wb_s2m_or1k_d_crypto_sha256_err;
wire        wb_s2m_or1k_d_crypto_sha256_rty;
wire [31:0] wb_m2s_or1k_d_fauxfs_cpu_adr;
wire [31:0] wb_m2s_or1k_d_fauxfs_cpu_dat;
wire  [3:0] wb_m2s_or1k_d_fauxfs_cpu_sel;
wire        wb_m2s_or1k_d_fauxfs_cpu_we;
wire        wb_m2s_or1k_d_fauxfs_cpu_cyc;
wire        wb_m2s_or1k_d_fauxfs_cpu_stb;
wire  [2:0] wb_m2s_or1k_d_fauxfs_cpu_cti;
wire  [1:0] wb_m2s_or1k_d_fauxfs_cpu_bte;
wire [31:0] wb_s2m_or1k_d_fauxfs_cpu_dat;
wire        wb_s2m_or1k_d_fauxfs_cpu_ack;
wire        wb_s2m_or1k_d_fauxfs_cpu_err;
wire        wb_s2m_or1k_d_fauxfs_cpu_rty;
wire [31:0] wb_m2s_or1k_d_nand_cpu_adr;
wire [31:0] wb_m2s_or1k_d_nand_cpu_dat;
wire  [3:0] wb_m2s_or1k_d_nand_cpu_sel;
wire        wb_m2s_or1k_d_nand_cpu_we;
wire        wb_m2s_or1k_d_nand_cpu_cyc;
wire        wb_m2s_or1k_d_nand_cpu_stb;
wire  [2:0] wb_m2s_or1k_d_nand_cpu_cti;
wire  [1:0] wb_m2s_or1k_d_nand_cpu_bte;
wire [31:0] wb_s2m_or1k_d_nand_cpu_dat;
wire        wb_s2m_or1k_d_nand_cpu_ack;
wire        wb_s2m_or1k_d_nand_cpu_err;
wire        wb_s2m_or1k_d_nand_cpu_rty;
wire [31:0] wb_m2s_or1k_d_bootrom0_adr;
wire [31:0] wb_m2s_or1k_d_bootrom0_dat;
wire  [3:0] wb_m2s_or1k_d_bootrom0_sel;
wire        wb_m2s_or1k_d_bootrom0_we;
wire        wb_m2s_or1k_d_bootrom0_cyc;
wire        wb_m2s_or1k_d_bootrom0_stb;
wire  [2:0] wb_m2s_or1k_d_bootrom0_cti;
wire  [1:0] wb_m2s_or1k_d_bootrom0_bte;
wire [31:0] wb_s2m_or1k_d_bootrom0_dat;
wire        wb_s2m_or1k_d_bootrom0_ack;
wire        wb_s2m_or1k_d_bootrom0_err;
wire        wb_s2m_or1k_d_bootrom0_rty;
wire [31:0] wb_m2s_dbg_rom0_adr;
wire [31:0] wb_m2s_dbg_rom0_dat;
wire  [3:0] wb_m2s_dbg_rom0_sel;
wire        wb_m2s_dbg_rom0_we;
wire        wb_m2s_dbg_rom0_cyc;
wire        wb_m2s_dbg_rom0_stb;
wire  [2:0] wb_m2s_dbg_rom0_cti;
wire  [1:0] wb_m2s_dbg_rom0_bte;
wire [31:0] wb_s2m_dbg_rom0_dat;
wire        wb_s2m_dbg_rom0_ack;
wire        wb_s2m_dbg_rom0_err;
wire        wb_s2m_dbg_rom0_rty;
wire [31:0] wb_m2s_dbg_ram0_adr;
wire [31:0] wb_m2s_dbg_ram0_dat;
wire  [3:0] wb_m2s_dbg_ram0_sel;
wire        wb_m2s_dbg_ram0_we;
wire        wb_m2s_dbg_ram0_cyc;
wire        wb_m2s_dbg_ram0_stb;
wire  [2:0] wb_m2s_dbg_ram0_cti;
wire  [1:0] wb_m2s_dbg_ram0_bte;
wire [31:0] wb_s2m_dbg_ram0_dat;
wire        wb_s2m_dbg_ram0_ack;
wire        wb_s2m_dbg_ram0_err;
wire        wb_s2m_dbg_ram0_rty;
wire [31:0] wb_m2s_dbg_uart0_adr;
wire [31:0] wb_m2s_dbg_uart0_dat;
wire  [3:0] wb_m2s_dbg_uart0_sel;
wire        wb_m2s_dbg_uart0_we;
wire        wb_m2s_dbg_uart0_cyc;
wire        wb_m2s_dbg_uart0_stb;
wire  [2:0] wb_m2s_dbg_uart0_cti;
wire  [1:0] wb_m2s_dbg_uart0_bte;
wire [31:0] wb_s2m_dbg_uart0_dat;
wire        wb_s2m_dbg_uart0_ack;
wire        wb_s2m_dbg_uart0_err;
wire        wb_s2m_dbg_uart0_rty;
wire [31:0] wb_m2s_dbg_gpio0_adr;
wire [31:0] wb_m2s_dbg_gpio0_dat;
wire  [3:0] wb_m2s_dbg_gpio0_sel;
wire        wb_m2s_dbg_gpio0_we;
wire        wb_m2s_dbg_gpio0_cyc;
wire        wb_m2s_dbg_gpio0_stb;
wire  [2:0] wb_m2s_dbg_gpio0_cti;
wire  [1:0] wb_m2s_dbg_gpio0_bte;
wire [31:0] wb_s2m_dbg_gpio0_dat;
wire        wb_s2m_dbg_gpio0_ack;
wire        wb_s2m_dbg_gpio0_err;
wire        wb_s2m_dbg_gpio0_rty;
wire [31:0] wb_m2s_dbg_trng_adr;
wire [31:0] wb_m2s_dbg_trng_dat;
wire  [3:0] wb_m2s_dbg_trng_sel;
wire        wb_m2s_dbg_trng_we;
wire        wb_m2s_dbg_trng_cyc;
wire        wb_m2s_dbg_trng_stb;
wire  [2:0] wb_m2s_dbg_trng_cti;
wire  [1:0] wb_m2s_dbg_trng_bte;
wire [31:0] wb_s2m_dbg_trng_dat;
wire        wb_s2m_dbg_trng_ack;
wire        wb_s2m_dbg_trng_err;
wire        wb_s2m_dbg_trng_rty;
wire [31:0] wb_m2s_dbg_crypto_aes_adr;
wire [31:0] wb_m2s_dbg_crypto_aes_dat;
wire  [3:0] wb_m2s_dbg_crypto_aes_sel;
wire        wb_m2s_dbg_crypto_aes_we;
wire        wb_m2s_dbg_crypto_aes_cyc;
wire        wb_m2s_dbg_crypto_aes_stb;
wire  [2:0] wb_m2s_dbg_crypto_aes_cti;
wire  [1:0] wb_m2s_dbg_crypto_aes_bte;
wire [31:0] wb_s2m_dbg_crypto_aes_dat;
wire        wb_s2m_dbg_crypto_aes_ack;
wire        wb_s2m_dbg_crypto_aes_err;
wire        wb_s2m_dbg_crypto_aes_rty;
wire [31:0] wb_m2s_dbg_crypto_sha256_adr;
wire [31:0] wb_m2s_dbg_crypto_sha256_dat;
wire  [3:0] wb_m2s_dbg_crypto_sha256_sel;
wire        wb_m2s_dbg_crypto_sha256_we;
wire        wb_m2s_dbg_crypto_sha256_cyc;
wire        wb_m2s_dbg_crypto_sha256_stb;
wire  [2:0] wb_m2s_dbg_crypto_sha256_cti;
wire  [1:0] wb_m2s_dbg_crypto_sha256_bte;
wire [31:0] wb_s2m_dbg_crypto_sha256_dat;
wire        wb_s2m_dbg_crypto_sha256_ack;
wire        wb_s2m_dbg_crypto_sha256_err;
wire        wb_s2m_dbg_crypto_sha256_rty;
wire [31:0] wb_m2s_dbg_fauxfs_cpu_adr;
wire [31:0] wb_m2s_dbg_fauxfs_cpu_dat;
wire  [3:0] wb_m2s_dbg_fauxfs_cpu_sel;
wire        wb_m2s_dbg_fauxfs_cpu_we;
wire        wb_m2s_dbg_fauxfs_cpu_cyc;
wire        wb_m2s_dbg_fauxfs_cpu_stb;
wire  [2:0] wb_m2s_dbg_fauxfs_cpu_cti;
wire  [1:0] wb_m2s_dbg_fauxfs_cpu_bte;
wire [31:0] wb_s2m_dbg_fauxfs_cpu_dat;
wire        wb_s2m_dbg_fauxfs_cpu_ack;
wire        wb_s2m_dbg_fauxfs_cpu_err;
wire        wb_s2m_dbg_fauxfs_cpu_rty;
wire [31:0] wb_m2s_dbg_nand_cpu_adr;
wire [31:0] wb_m2s_dbg_nand_cpu_dat;
wire  [3:0] wb_m2s_dbg_nand_cpu_sel;
wire        wb_m2s_dbg_nand_cpu_we;
wire        wb_m2s_dbg_nand_cpu_cyc;
wire        wb_m2s_dbg_nand_cpu_stb;
wire  [2:0] wb_m2s_dbg_nand_cpu_cti;
wire  [1:0] wb_m2s_dbg_nand_cpu_bte;
wire [31:0] wb_s2m_dbg_nand_cpu_dat;
wire        wb_s2m_dbg_nand_cpu_ack;
wire        wb_s2m_dbg_nand_cpu_err;
wire        wb_s2m_dbg_nand_cpu_rty;
wire [31:0] wb_m2s_dbg_bootrom0_adr;
wire [31:0] wb_m2s_dbg_bootrom0_dat;
wire  [3:0] wb_m2s_dbg_bootrom0_sel;
wire        wb_m2s_dbg_bootrom0_we;
wire        wb_m2s_dbg_bootrom0_cyc;
wire        wb_m2s_dbg_bootrom0_stb;
wire  [2:0] wb_m2s_dbg_bootrom0_cti;
wire  [1:0] wb_m2s_dbg_bootrom0_bte;
wire [31:0] wb_s2m_dbg_bootrom0_dat;
wire        wb_s2m_dbg_bootrom0_ack;
wire        wb_s2m_dbg_bootrom0_err;
wire        wb_s2m_dbg_bootrom0_rty;
wire [31:0] wb_m2s_resize_uart0_adr;
wire [31:0] wb_m2s_resize_uart0_dat;
wire  [3:0] wb_m2s_resize_uart0_sel;
wire        wb_m2s_resize_uart0_we;
wire        wb_m2s_resize_uart0_cyc;
wire        wb_m2s_resize_uart0_stb;
wire  [2:0] wb_m2s_resize_uart0_cti;
wire  [1:0] wb_m2s_resize_uart0_bte;
wire [31:0] wb_s2m_resize_uart0_dat;
wire        wb_s2m_resize_uart0_ack;
wire        wb_s2m_resize_uart0_err;
wire        wb_s2m_resize_uart0_rty;
wire [31:0] wb_m2s_resize_gpio0_adr;
wire [31:0] wb_m2s_resize_gpio0_dat;
wire  [3:0] wb_m2s_resize_gpio0_sel;
wire        wb_m2s_resize_gpio0_we;
wire        wb_m2s_resize_gpio0_cyc;
wire        wb_m2s_resize_gpio0_stb;
wire  [2:0] wb_m2s_resize_gpio0_cti;
wire  [1:0] wb_m2s_resize_gpio0_bte;
wire [31:0] wb_s2m_resize_gpio0_dat;
wire        wb_s2m_resize_gpio0_ack;
wire        wb_s2m_resize_gpio0_err;
wire        wb_s2m_resize_gpio0_rty;
wire [31:0] wb_m2s_resize_trng_adr;
wire [31:0] wb_m2s_resize_trng_dat;
wire  [3:0] wb_m2s_resize_trng_sel;
wire        wb_m2s_resize_trng_we;
wire        wb_m2s_resize_trng_cyc;
wire        wb_m2s_resize_trng_stb;
wire  [2:0] wb_m2s_resize_trng_cti;
wire  [1:0] wb_m2s_resize_trng_bte;
wire [31:0] wb_s2m_resize_trng_dat;
wire        wb_s2m_resize_trng_ack;
wire        wb_s2m_resize_trng_err;
wire        wb_s2m_resize_trng_rty;

wb_mux
  #(.num_slaves (2),
    .MATCH_ADDR ({32'h00100000, 32'hf0000100}),
    .MATCH_MASK ({32'hffff0000, 32'hffffff80}))
 wb_mux_or1k_i
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_or1k_i_adr_i),
    .wbm_dat_i (wb_or1k_i_dat_i),
    .wbm_sel_i (wb_or1k_i_sel_i),
    .wbm_we_i  (wb_or1k_i_we_i),
    .wbm_cyc_i (wb_or1k_i_cyc_i),
    .wbm_stb_i (wb_or1k_i_stb_i),
    .wbm_cti_i (wb_or1k_i_cti_i),
    .wbm_bte_i (wb_or1k_i_bte_i),
    .wbm_dat_o (wb_or1k_i_dat_o),
    .wbm_ack_o (wb_or1k_i_ack_o),
    .wbm_err_o (wb_or1k_i_err_o),
    .wbm_rty_o (wb_or1k_i_rty_o),
    .wbs_adr_o ({wb_m2s_or1k_i_rom0_adr, wb_m2s_or1k_i_bootrom0_adr}),
    .wbs_dat_o ({wb_m2s_or1k_i_rom0_dat, wb_m2s_or1k_i_bootrom0_dat}),
    .wbs_sel_o ({wb_m2s_or1k_i_rom0_sel, wb_m2s_or1k_i_bootrom0_sel}),
    .wbs_we_o  ({wb_m2s_or1k_i_rom0_we, wb_m2s_or1k_i_bootrom0_we}),
    .wbs_cyc_o ({wb_m2s_or1k_i_rom0_cyc, wb_m2s_or1k_i_bootrom0_cyc}),
    .wbs_stb_o ({wb_m2s_or1k_i_rom0_stb, wb_m2s_or1k_i_bootrom0_stb}),
    .wbs_cti_o ({wb_m2s_or1k_i_rom0_cti, wb_m2s_or1k_i_bootrom0_cti}),
    .wbs_bte_o ({wb_m2s_or1k_i_rom0_bte, wb_m2s_or1k_i_bootrom0_bte}),
    .wbs_dat_i ({wb_s2m_or1k_i_rom0_dat, wb_s2m_or1k_i_bootrom0_dat}),
    .wbs_ack_i ({wb_s2m_or1k_i_rom0_ack, wb_s2m_or1k_i_bootrom0_ack}),
    .wbs_err_i ({wb_s2m_or1k_i_rom0_err, wb_s2m_or1k_i_bootrom0_err}),
    .wbs_rty_i ({wb_s2m_or1k_i_rom0_rty, wb_s2m_or1k_i_bootrom0_rty}));

wb_mux
  #(.num_slaves (10),
    .MATCH_ADDR ({32'h00100000, 32'h00200000, 32'h90000000, 32'h91000000, 32'h92000000, 32'h93000000, 32'h94000000, 32'h98000000, 32'ha0000000, 32'hf0000100}),
    .MATCH_MASK ({32'hffff0000, 32'hfffe0000, 32'hffffffe0, 32'hfffffffe, 32'hffffffff, 32'hffffff80, 32'hffffff00, 32'hffffe000, 32'hffffe000, 32'hffffff80}))
 wb_mux_or1k_d
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_or1k_d_adr_i),
    .wbm_dat_i (wb_or1k_d_dat_i),
    .wbm_sel_i (wb_or1k_d_sel_i),
    .wbm_we_i  (wb_or1k_d_we_i),
    .wbm_cyc_i (wb_or1k_d_cyc_i),
    .wbm_stb_i (wb_or1k_d_stb_i),
    .wbm_cti_i (wb_or1k_d_cti_i),
    .wbm_bte_i (wb_or1k_d_bte_i),
    .wbm_dat_o (wb_or1k_d_dat_o),
    .wbm_ack_o (wb_or1k_d_ack_o),
    .wbm_err_o (wb_or1k_d_err_o),
    .wbm_rty_o (wb_or1k_d_rty_o),
    .wbs_adr_o ({wb_m2s_or1k_d_rom0_adr, wb_m2s_or1k_d_ram0_adr, wb_m2s_or1k_d_uart0_adr, wb_m2s_or1k_d_gpio0_adr, wb_m2s_or1k_d_trng_adr, wb_m2s_or1k_d_crypto_aes_adr, wb_m2s_or1k_d_crypto_sha256_adr, wb_m2s_or1k_d_fauxfs_cpu_adr, wb_m2s_or1k_d_nand_cpu_adr, wb_m2s_or1k_d_bootrom0_adr}),
    .wbs_dat_o ({wb_m2s_or1k_d_rom0_dat, wb_m2s_or1k_d_ram0_dat, wb_m2s_or1k_d_uart0_dat, wb_m2s_or1k_d_gpio0_dat, wb_m2s_or1k_d_trng_dat, wb_m2s_or1k_d_crypto_aes_dat, wb_m2s_or1k_d_crypto_sha256_dat, wb_m2s_or1k_d_fauxfs_cpu_dat, wb_m2s_or1k_d_nand_cpu_dat, wb_m2s_or1k_d_bootrom0_dat}),
    .wbs_sel_o ({wb_m2s_or1k_d_rom0_sel, wb_m2s_or1k_d_ram0_sel, wb_m2s_or1k_d_uart0_sel, wb_m2s_or1k_d_gpio0_sel, wb_m2s_or1k_d_trng_sel, wb_m2s_or1k_d_crypto_aes_sel, wb_m2s_or1k_d_crypto_sha256_sel, wb_m2s_or1k_d_fauxfs_cpu_sel, wb_m2s_or1k_d_nand_cpu_sel, wb_m2s_or1k_d_bootrom0_sel}),
    .wbs_we_o  ({wb_m2s_or1k_d_rom0_we, wb_m2s_or1k_d_ram0_we, wb_m2s_or1k_d_uart0_we, wb_m2s_or1k_d_gpio0_we, wb_m2s_or1k_d_trng_we, wb_m2s_or1k_d_crypto_aes_we, wb_m2s_or1k_d_crypto_sha256_we, wb_m2s_or1k_d_fauxfs_cpu_we, wb_m2s_or1k_d_nand_cpu_we, wb_m2s_or1k_d_bootrom0_we}),
    .wbs_cyc_o ({wb_m2s_or1k_d_rom0_cyc, wb_m2s_or1k_d_ram0_cyc, wb_m2s_or1k_d_uart0_cyc, wb_m2s_or1k_d_gpio0_cyc, wb_m2s_or1k_d_trng_cyc, wb_m2s_or1k_d_crypto_aes_cyc, wb_m2s_or1k_d_crypto_sha256_cyc, wb_m2s_or1k_d_fauxfs_cpu_cyc, wb_m2s_or1k_d_nand_cpu_cyc, wb_m2s_or1k_d_bootrom0_cyc}),
    .wbs_stb_o ({wb_m2s_or1k_d_rom0_stb, wb_m2s_or1k_d_ram0_stb, wb_m2s_or1k_d_uart0_stb, wb_m2s_or1k_d_gpio0_stb, wb_m2s_or1k_d_trng_stb, wb_m2s_or1k_d_crypto_aes_stb, wb_m2s_or1k_d_crypto_sha256_stb, wb_m2s_or1k_d_fauxfs_cpu_stb, wb_m2s_or1k_d_nand_cpu_stb, wb_m2s_or1k_d_bootrom0_stb}),
    .wbs_cti_o ({wb_m2s_or1k_d_rom0_cti, wb_m2s_or1k_d_ram0_cti, wb_m2s_or1k_d_uart0_cti, wb_m2s_or1k_d_gpio0_cti, wb_m2s_or1k_d_trng_cti, wb_m2s_or1k_d_crypto_aes_cti, wb_m2s_or1k_d_crypto_sha256_cti, wb_m2s_or1k_d_fauxfs_cpu_cti, wb_m2s_or1k_d_nand_cpu_cti, wb_m2s_or1k_d_bootrom0_cti}),
    .wbs_bte_o ({wb_m2s_or1k_d_rom0_bte, wb_m2s_or1k_d_ram0_bte, wb_m2s_or1k_d_uart0_bte, wb_m2s_or1k_d_gpio0_bte, wb_m2s_or1k_d_trng_bte, wb_m2s_or1k_d_crypto_aes_bte, wb_m2s_or1k_d_crypto_sha256_bte, wb_m2s_or1k_d_fauxfs_cpu_bte, wb_m2s_or1k_d_nand_cpu_bte, wb_m2s_or1k_d_bootrom0_bte}),
    .wbs_dat_i ({wb_s2m_or1k_d_rom0_dat, wb_s2m_or1k_d_ram0_dat, wb_s2m_or1k_d_uart0_dat, wb_s2m_or1k_d_gpio0_dat, wb_s2m_or1k_d_trng_dat, wb_s2m_or1k_d_crypto_aes_dat, wb_s2m_or1k_d_crypto_sha256_dat, wb_s2m_or1k_d_fauxfs_cpu_dat, wb_s2m_or1k_d_nand_cpu_dat, wb_s2m_or1k_d_bootrom0_dat}),
    .wbs_ack_i ({wb_s2m_or1k_d_rom0_ack, wb_s2m_or1k_d_ram0_ack, wb_s2m_or1k_d_uart0_ack, wb_s2m_or1k_d_gpio0_ack, wb_s2m_or1k_d_trng_ack, wb_s2m_or1k_d_crypto_aes_ack, wb_s2m_or1k_d_crypto_sha256_ack, wb_s2m_or1k_d_fauxfs_cpu_ack, wb_s2m_or1k_d_nand_cpu_ack, wb_s2m_or1k_d_bootrom0_ack}),
    .wbs_err_i ({wb_s2m_or1k_d_rom0_err, wb_s2m_or1k_d_ram0_err, wb_s2m_or1k_d_uart0_err, wb_s2m_or1k_d_gpio0_err, wb_s2m_or1k_d_trng_err, wb_s2m_or1k_d_crypto_aes_err, wb_s2m_or1k_d_crypto_sha256_err, wb_s2m_or1k_d_fauxfs_cpu_err, wb_s2m_or1k_d_nand_cpu_err, wb_s2m_or1k_d_bootrom0_err}),
    .wbs_rty_i ({wb_s2m_or1k_d_rom0_rty, wb_s2m_or1k_d_ram0_rty, wb_s2m_or1k_d_uart0_rty, wb_s2m_or1k_d_gpio0_rty, wb_s2m_or1k_d_trng_rty, wb_s2m_or1k_d_crypto_aes_rty, wb_s2m_or1k_d_crypto_sha256_rty, wb_s2m_or1k_d_fauxfs_cpu_rty, wb_s2m_or1k_d_nand_cpu_rty, wb_s2m_or1k_d_bootrom0_rty}));

wb_mux
  #(.num_slaves (10),
    .MATCH_ADDR ({32'h00100000, 32'h00200000, 32'h90000000, 32'h91000000, 32'h92000000, 32'h93000000, 32'h94000000, 32'h98000000, 32'ha0000000, 32'hf0000100}),
    .MATCH_MASK ({32'hffff0000, 32'hfffe0000, 32'hffffffe0, 32'hfffffffe, 32'hffffffff, 32'hffffff80, 32'hffffff00, 32'hffffe000, 32'hffffe000, 32'hffffff80}))
 wb_mux_dbg
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_dbg_adr_i),
    .wbm_dat_i (wb_dbg_dat_i),
    .wbm_sel_i (wb_dbg_sel_i),
    .wbm_we_i  (wb_dbg_we_i),
    .wbm_cyc_i (wb_dbg_cyc_i),
    .wbm_stb_i (wb_dbg_stb_i),
    .wbm_cti_i (wb_dbg_cti_i),
    .wbm_bte_i (wb_dbg_bte_i),
    .wbm_dat_o (wb_dbg_dat_o),
    .wbm_ack_o (wb_dbg_ack_o),
    .wbm_err_o (wb_dbg_err_o),
    .wbm_rty_o (wb_dbg_rty_o),
    .wbs_adr_o ({wb_m2s_dbg_rom0_adr, wb_m2s_dbg_ram0_adr, wb_m2s_dbg_uart0_adr, wb_m2s_dbg_gpio0_adr, wb_m2s_dbg_trng_adr, wb_m2s_dbg_crypto_aes_adr, wb_m2s_dbg_crypto_sha256_adr, wb_m2s_dbg_fauxfs_cpu_adr, wb_m2s_dbg_nand_cpu_adr, wb_m2s_dbg_bootrom0_adr}),
    .wbs_dat_o ({wb_m2s_dbg_rom0_dat, wb_m2s_dbg_ram0_dat, wb_m2s_dbg_uart0_dat, wb_m2s_dbg_gpio0_dat, wb_m2s_dbg_trng_dat, wb_m2s_dbg_crypto_aes_dat, wb_m2s_dbg_crypto_sha256_dat, wb_m2s_dbg_fauxfs_cpu_dat, wb_m2s_dbg_nand_cpu_dat, wb_m2s_dbg_bootrom0_dat}),
    .wbs_sel_o ({wb_m2s_dbg_rom0_sel, wb_m2s_dbg_ram0_sel, wb_m2s_dbg_uart0_sel, wb_m2s_dbg_gpio0_sel, wb_m2s_dbg_trng_sel, wb_m2s_dbg_crypto_aes_sel, wb_m2s_dbg_crypto_sha256_sel, wb_m2s_dbg_fauxfs_cpu_sel, wb_m2s_dbg_nand_cpu_sel, wb_m2s_dbg_bootrom0_sel}),
    .wbs_we_o  ({wb_m2s_dbg_rom0_we, wb_m2s_dbg_ram0_we, wb_m2s_dbg_uart0_we, wb_m2s_dbg_gpio0_we, wb_m2s_dbg_trng_we, wb_m2s_dbg_crypto_aes_we, wb_m2s_dbg_crypto_sha256_we, wb_m2s_dbg_fauxfs_cpu_we, wb_m2s_dbg_nand_cpu_we, wb_m2s_dbg_bootrom0_we}),
    .wbs_cyc_o ({wb_m2s_dbg_rom0_cyc, wb_m2s_dbg_ram0_cyc, wb_m2s_dbg_uart0_cyc, wb_m2s_dbg_gpio0_cyc, wb_m2s_dbg_trng_cyc, wb_m2s_dbg_crypto_aes_cyc, wb_m2s_dbg_crypto_sha256_cyc, wb_m2s_dbg_fauxfs_cpu_cyc, wb_m2s_dbg_nand_cpu_cyc, wb_m2s_dbg_bootrom0_cyc}),
    .wbs_stb_o ({wb_m2s_dbg_rom0_stb, wb_m2s_dbg_ram0_stb, wb_m2s_dbg_uart0_stb, wb_m2s_dbg_gpio0_stb, wb_m2s_dbg_trng_stb, wb_m2s_dbg_crypto_aes_stb, wb_m2s_dbg_crypto_sha256_stb, wb_m2s_dbg_fauxfs_cpu_stb, wb_m2s_dbg_nand_cpu_stb, wb_m2s_dbg_bootrom0_stb}),
    .wbs_cti_o ({wb_m2s_dbg_rom0_cti, wb_m2s_dbg_ram0_cti, wb_m2s_dbg_uart0_cti, wb_m2s_dbg_gpio0_cti, wb_m2s_dbg_trng_cti, wb_m2s_dbg_crypto_aes_cti, wb_m2s_dbg_crypto_sha256_cti, wb_m2s_dbg_fauxfs_cpu_cti, wb_m2s_dbg_nand_cpu_cti, wb_m2s_dbg_bootrom0_cti}),
    .wbs_bte_o ({wb_m2s_dbg_rom0_bte, wb_m2s_dbg_ram0_bte, wb_m2s_dbg_uart0_bte, wb_m2s_dbg_gpio0_bte, wb_m2s_dbg_trng_bte, wb_m2s_dbg_crypto_aes_bte, wb_m2s_dbg_crypto_sha256_bte, wb_m2s_dbg_fauxfs_cpu_bte, wb_m2s_dbg_nand_cpu_bte, wb_m2s_dbg_bootrom0_bte}),
    .wbs_dat_i ({wb_s2m_dbg_rom0_dat, wb_s2m_dbg_ram0_dat, wb_s2m_dbg_uart0_dat, wb_s2m_dbg_gpio0_dat, wb_s2m_dbg_trng_dat, wb_s2m_dbg_crypto_aes_dat, wb_s2m_dbg_crypto_sha256_dat, wb_s2m_dbg_fauxfs_cpu_dat, wb_s2m_dbg_nand_cpu_dat, wb_s2m_dbg_bootrom0_dat}),
    .wbs_ack_i ({wb_s2m_dbg_rom0_ack, wb_s2m_dbg_ram0_ack, wb_s2m_dbg_uart0_ack, wb_s2m_dbg_gpio0_ack, wb_s2m_dbg_trng_ack, wb_s2m_dbg_crypto_aes_ack, wb_s2m_dbg_crypto_sha256_ack, wb_s2m_dbg_fauxfs_cpu_ack, wb_s2m_dbg_nand_cpu_ack, wb_s2m_dbg_bootrom0_ack}),
    .wbs_err_i ({wb_s2m_dbg_rom0_err, wb_s2m_dbg_ram0_err, wb_s2m_dbg_uart0_err, wb_s2m_dbg_gpio0_err, wb_s2m_dbg_trng_err, wb_s2m_dbg_crypto_aes_err, wb_s2m_dbg_crypto_sha256_err, wb_s2m_dbg_fauxfs_cpu_err, wb_s2m_dbg_nand_cpu_err, wb_s2m_dbg_bootrom0_err}),
    .wbs_rty_i ({wb_s2m_dbg_rom0_rty, wb_s2m_dbg_ram0_rty, wb_s2m_dbg_uart0_rty, wb_s2m_dbg_gpio0_rty, wb_s2m_dbg_trng_rty, wb_s2m_dbg_crypto_aes_rty, wb_s2m_dbg_crypto_sha256_rty, wb_s2m_dbg_fauxfs_cpu_rty, wb_s2m_dbg_nand_cpu_rty, wb_s2m_dbg_bootrom0_rty}));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_rom0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_i_rom0_adr, wb_m2s_or1k_d_rom0_adr, wb_m2s_dbg_rom0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_i_rom0_dat, wb_m2s_or1k_d_rom0_dat, wb_m2s_dbg_rom0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_i_rom0_sel, wb_m2s_or1k_d_rom0_sel, wb_m2s_dbg_rom0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_i_rom0_we, wb_m2s_or1k_d_rom0_we, wb_m2s_dbg_rom0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_i_rom0_cyc, wb_m2s_or1k_d_rom0_cyc, wb_m2s_dbg_rom0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_i_rom0_stb, wb_m2s_or1k_d_rom0_stb, wb_m2s_dbg_rom0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_i_rom0_cti, wb_m2s_or1k_d_rom0_cti, wb_m2s_dbg_rom0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_i_rom0_bte, wb_m2s_or1k_d_rom0_bte, wb_m2s_dbg_rom0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_i_rom0_dat, wb_s2m_or1k_d_rom0_dat, wb_s2m_dbg_rom0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_i_rom0_ack, wb_s2m_or1k_d_rom0_ack, wb_s2m_dbg_rom0_ack}),
    .wbm_err_o ({wb_s2m_or1k_i_rom0_err, wb_s2m_or1k_d_rom0_err, wb_s2m_dbg_rom0_err}),
    .wbm_rty_o ({wb_s2m_or1k_i_rom0_rty, wb_s2m_or1k_d_rom0_rty, wb_s2m_dbg_rom0_rty}),
    .wbs_adr_o (wb_rom0_adr_o),
    .wbs_dat_o (wb_rom0_dat_o),
    .wbs_sel_o (wb_rom0_sel_o),
    .wbs_we_o  (wb_rom0_we_o),
    .wbs_cyc_o (wb_rom0_cyc_o),
    .wbs_stb_o (wb_rom0_stb_o),
    .wbs_cti_o (wb_rom0_cti_o),
    .wbs_bte_o (wb_rom0_bte_o),
    .wbs_dat_i (wb_rom0_dat_i),
    .wbs_ack_i (wb_rom0_ack_i),
    .wbs_err_i (wb_rom0_err_i),
    .wbs_rty_i (wb_rom0_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_ram0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_ram0_adr, wb_m2s_dbg_ram0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_ram0_dat, wb_m2s_dbg_ram0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_ram0_sel, wb_m2s_dbg_ram0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_ram0_we, wb_m2s_dbg_ram0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_ram0_cyc, wb_m2s_dbg_ram0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_ram0_stb, wb_m2s_dbg_ram0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_ram0_cti, wb_m2s_dbg_ram0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_ram0_bte, wb_m2s_dbg_ram0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_ram0_dat, wb_s2m_dbg_ram0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_ram0_ack, wb_s2m_dbg_ram0_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_ram0_err, wb_s2m_dbg_ram0_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_ram0_rty, wb_s2m_dbg_ram0_rty}),
    .wbs_adr_o (wb_ram0_adr_o),
    .wbs_dat_o (wb_ram0_dat_o),
    .wbs_sel_o (wb_ram0_sel_o),
    .wbs_we_o  (wb_ram0_we_o),
    .wbs_cyc_o (wb_ram0_cyc_o),
    .wbs_stb_o (wb_ram0_stb_o),
    .wbs_cti_o (wb_ram0_cti_o),
    .wbs_bte_o (wb_ram0_bte_o),
    .wbs_dat_i (wb_ram0_dat_i),
    .wbs_ack_i (wb_ram0_ack_i),
    .wbs_err_i (wb_ram0_err_i),
    .wbs_rty_i (wb_ram0_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_uart0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_uart0_adr, wb_m2s_dbg_uart0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_uart0_dat, wb_m2s_dbg_uart0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_uart0_sel, wb_m2s_dbg_uart0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_uart0_we, wb_m2s_dbg_uart0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_uart0_cyc, wb_m2s_dbg_uart0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_uart0_stb, wb_m2s_dbg_uart0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_uart0_cti, wb_m2s_dbg_uart0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_uart0_bte, wb_m2s_dbg_uart0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_uart0_dat, wb_s2m_dbg_uart0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_uart0_ack, wb_s2m_dbg_uart0_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_uart0_err, wb_s2m_dbg_uart0_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_uart0_rty, wb_s2m_dbg_uart0_rty}),
    .wbs_adr_o (wb_m2s_resize_uart0_adr),
    .wbs_dat_o (wb_m2s_resize_uart0_dat),
    .wbs_sel_o (wb_m2s_resize_uart0_sel),
    .wbs_we_o  (wb_m2s_resize_uart0_we),
    .wbs_cyc_o (wb_m2s_resize_uart0_cyc),
    .wbs_stb_o (wb_m2s_resize_uart0_stb),
    .wbs_cti_o (wb_m2s_resize_uart0_cti),
    .wbs_bte_o (wb_m2s_resize_uart0_bte),
    .wbs_dat_i (wb_s2m_resize_uart0_dat),
    .wbs_ack_i (wb_s2m_resize_uart0_ack),
    .wbs_err_i (wb_s2m_resize_uart0_err),
    .wbs_rty_i (wb_s2m_resize_uart0_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_uart0
   (.wbm_adr_i (wb_m2s_resize_uart0_adr),
    .wbm_dat_i (wb_m2s_resize_uart0_dat),
    .wbm_sel_i (wb_m2s_resize_uart0_sel),
    .wbm_we_i  (wb_m2s_resize_uart0_we),
    .wbm_cyc_i (wb_m2s_resize_uart0_cyc),
    .wbm_stb_i (wb_m2s_resize_uart0_stb),
    .wbm_cti_i (wb_m2s_resize_uart0_cti),
    .wbm_bte_i (wb_m2s_resize_uart0_bte),
    .wbm_dat_o (wb_s2m_resize_uart0_dat),
    .wbm_ack_o (wb_s2m_resize_uart0_ack),
    .wbm_err_o (wb_s2m_resize_uart0_err),
    .wbm_rty_o (wb_s2m_resize_uart0_rty),
    .wbs_adr_o (wb_uart0_adr_o),
    .wbs_dat_o (wb_uart0_dat_o),
    .wbs_we_o  (wb_uart0_we_o),
    .wbs_cyc_o (wb_uart0_cyc_o),
    .wbs_stb_o (wb_uart0_stb_o),
    .wbs_cti_o (wb_uart0_cti_o),
    .wbs_bte_o (wb_uart0_bte_o),
    .wbs_dat_i (wb_uart0_dat_i),
    .wbs_ack_i (wb_uart0_ack_i),
    .wbs_err_i (wb_uart0_err_i),
    .wbs_rty_i (wb_uart0_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_gpio0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_gpio0_adr, wb_m2s_dbg_gpio0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_gpio0_dat, wb_m2s_dbg_gpio0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_gpio0_sel, wb_m2s_dbg_gpio0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_gpio0_we, wb_m2s_dbg_gpio0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_gpio0_cyc, wb_m2s_dbg_gpio0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_gpio0_stb, wb_m2s_dbg_gpio0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_gpio0_cti, wb_m2s_dbg_gpio0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_gpio0_bte, wb_m2s_dbg_gpio0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_gpio0_dat, wb_s2m_dbg_gpio0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_gpio0_ack, wb_s2m_dbg_gpio0_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_gpio0_err, wb_s2m_dbg_gpio0_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_gpio0_rty, wb_s2m_dbg_gpio0_rty}),
    .wbs_adr_o (wb_m2s_resize_gpio0_adr),
    .wbs_dat_o (wb_m2s_resize_gpio0_dat),
    .wbs_sel_o (wb_m2s_resize_gpio0_sel),
    .wbs_we_o  (wb_m2s_resize_gpio0_we),
    .wbs_cyc_o (wb_m2s_resize_gpio0_cyc),
    .wbs_stb_o (wb_m2s_resize_gpio0_stb),
    .wbs_cti_o (wb_m2s_resize_gpio0_cti),
    .wbs_bte_o (wb_m2s_resize_gpio0_bte),
    .wbs_dat_i (wb_s2m_resize_gpio0_dat),
    .wbs_ack_i (wb_s2m_resize_gpio0_ack),
    .wbs_err_i (wb_s2m_resize_gpio0_err),
    .wbs_rty_i (wb_s2m_resize_gpio0_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_gpio0
   (.wbm_adr_i (wb_m2s_resize_gpio0_adr),
    .wbm_dat_i (wb_m2s_resize_gpio0_dat),
    .wbm_sel_i (wb_m2s_resize_gpio0_sel),
    .wbm_we_i  (wb_m2s_resize_gpio0_we),
    .wbm_cyc_i (wb_m2s_resize_gpio0_cyc),
    .wbm_stb_i (wb_m2s_resize_gpio0_stb),
    .wbm_cti_i (wb_m2s_resize_gpio0_cti),
    .wbm_bte_i (wb_m2s_resize_gpio0_bte),
    .wbm_dat_o (wb_s2m_resize_gpio0_dat),
    .wbm_ack_o (wb_s2m_resize_gpio0_ack),
    .wbm_err_o (wb_s2m_resize_gpio0_err),
    .wbm_rty_o (wb_s2m_resize_gpio0_rty),
    .wbs_adr_o (wb_gpio0_adr_o),
    .wbs_dat_o (wb_gpio0_dat_o),
    .wbs_we_o  (wb_gpio0_we_o),
    .wbs_cyc_o (wb_gpio0_cyc_o),
    .wbs_stb_o (wb_gpio0_stb_o),
    .wbs_cti_o (wb_gpio0_cti_o),
    .wbs_bte_o (wb_gpio0_bte_o),
    .wbs_dat_i (wb_gpio0_dat_i),
    .wbs_ack_i (wb_gpio0_ack_i),
    .wbs_err_i (wb_gpio0_err_i),
    .wbs_rty_i (wb_gpio0_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_trng
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_trng_adr, wb_m2s_dbg_trng_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_trng_dat, wb_m2s_dbg_trng_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_trng_sel, wb_m2s_dbg_trng_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_trng_we, wb_m2s_dbg_trng_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_trng_cyc, wb_m2s_dbg_trng_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_trng_stb, wb_m2s_dbg_trng_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_trng_cti, wb_m2s_dbg_trng_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_trng_bte, wb_m2s_dbg_trng_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_trng_dat, wb_s2m_dbg_trng_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_trng_ack, wb_s2m_dbg_trng_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_trng_err, wb_s2m_dbg_trng_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_trng_rty, wb_s2m_dbg_trng_rty}),
    .wbs_adr_o (wb_m2s_resize_trng_adr),
    .wbs_dat_o (wb_m2s_resize_trng_dat),
    .wbs_sel_o (wb_m2s_resize_trng_sel),
    .wbs_we_o  (wb_m2s_resize_trng_we),
    .wbs_cyc_o (wb_m2s_resize_trng_cyc),
    .wbs_stb_o (wb_m2s_resize_trng_stb),
    .wbs_cti_o (wb_m2s_resize_trng_cti),
    .wbs_bte_o (wb_m2s_resize_trng_bte),
    .wbs_dat_i (wb_s2m_resize_trng_dat),
    .wbs_ack_i (wb_s2m_resize_trng_ack),
    .wbs_err_i (wb_s2m_resize_trng_err),
    .wbs_rty_i (wb_s2m_resize_trng_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_trng
   (.wbm_adr_i (wb_m2s_resize_trng_adr),
    .wbm_dat_i (wb_m2s_resize_trng_dat),
    .wbm_sel_i (wb_m2s_resize_trng_sel),
    .wbm_we_i  (wb_m2s_resize_trng_we),
    .wbm_cyc_i (wb_m2s_resize_trng_cyc),
    .wbm_stb_i (wb_m2s_resize_trng_stb),
    .wbm_cti_i (wb_m2s_resize_trng_cti),
    .wbm_bte_i (wb_m2s_resize_trng_bte),
    .wbm_dat_o (wb_s2m_resize_trng_dat),
    .wbm_ack_o (wb_s2m_resize_trng_ack),
    .wbm_err_o (wb_s2m_resize_trng_err),
    .wbm_rty_o (wb_s2m_resize_trng_rty),
    .wbs_adr_o (wb_trng_adr_o),
    .wbs_dat_o (wb_trng_dat_o),
    .wbs_we_o  (wb_trng_we_o),
    .wbs_cyc_o (wb_trng_cyc_o),
    .wbs_stb_o (wb_trng_stb_o),
    .wbs_cti_o (wb_trng_cti_o),
    .wbs_bte_o (wb_trng_bte_o),
    .wbs_dat_i (wb_trng_dat_i),
    .wbs_ack_i (wb_trng_ack_i),
    .wbs_err_i (wb_trng_err_i),
    .wbs_rty_i (wb_trng_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_crypto_aes
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_crypto_aes_adr, wb_m2s_dbg_crypto_aes_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_crypto_aes_dat, wb_m2s_dbg_crypto_aes_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_crypto_aes_sel, wb_m2s_dbg_crypto_aes_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_crypto_aes_we, wb_m2s_dbg_crypto_aes_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_crypto_aes_cyc, wb_m2s_dbg_crypto_aes_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_crypto_aes_stb, wb_m2s_dbg_crypto_aes_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_crypto_aes_cti, wb_m2s_dbg_crypto_aes_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_crypto_aes_bte, wb_m2s_dbg_crypto_aes_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_crypto_aes_dat, wb_s2m_dbg_crypto_aes_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_crypto_aes_ack, wb_s2m_dbg_crypto_aes_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_crypto_aes_err, wb_s2m_dbg_crypto_aes_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_crypto_aes_rty, wb_s2m_dbg_crypto_aes_rty}),
    .wbs_adr_o (wb_crypto_aes_adr_o),
    .wbs_dat_o (wb_crypto_aes_dat_o),
    .wbs_sel_o (wb_crypto_aes_sel_o),
    .wbs_we_o  (wb_crypto_aes_we_o),
    .wbs_cyc_o (wb_crypto_aes_cyc_o),
    .wbs_stb_o (wb_crypto_aes_stb_o),
    .wbs_cti_o (wb_crypto_aes_cti_o),
    .wbs_bte_o (wb_crypto_aes_bte_o),
    .wbs_dat_i (wb_crypto_aes_dat_i),
    .wbs_ack_i (wb_crypto_aes_ack_i),
    .wbs_err_i (wb_crypto_aes_err_i),
    .wbs_rty_i (wb_crypto_aes_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_crypto_sha256
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_crypto_sha256_adr, wb_m2s_dbg_crypto_sha256_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_crypto_sha256_dat, wb_m2s_dbg_crypto_sha256_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_crypto_sha256_sel, wb_m2s_dbg_crypto_sha256_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_crypto_sha256_we, wb_m2s_dbg_crypto_sha256_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_crypto_sha256_cyc, wb_m2s_dbg_crypto_sha256_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_crypto_sha256_stb, wb_m2s_dbg_crypto_sha256_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_crypto_sha256_cti, wb_m2s_dbg_crypto_sha256_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_crypto_sha256_bte, wb_m2s_dbg_crypto_sha256_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_crypto_sha256_dat, wb_s2m_dbg_crypto_sha256_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_crypto_sha256_ack, wb_s2m_dbg_crypto_sha256_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_crypto_sha256_err, wb_s2m_dbg_crypto_sha256_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_crypto_sha256_rty, wb_s2m_dbg_crypto_sha256_rty}),
    .wbs_adr_o (wb_crypto_sha256_adr_o),
    .wbs_dat_o (wb_crypto_sha256_dat_o),
    .wbs_sel_o (wb_crypto_sha256_sel_o),
    .wbs_we_o  (wb_crypto_sha256_we_o),
    .wbs_cyc_o (wb_crypto_sha256_cyc_o),
    .wbs_stb_o (wb_crypto_sha256_stb_o),
    .wbs_cti_o (wb_crypto_sha256_cti_o),
    .wbs_bte_o (wb_crypto_sha256_bte_o),
    .wbs_dat_i (wb_crypto_sha256_dat_i),
    .wbs_ack_i (wb_crypto_sha256_ack_i),
    .wbs_err_i (wb_crypto_sha256_err_i),
    .wbs_rty_i (wb_crypto_sha256_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_fauxfs_cpu
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_fauxfs_cpu_adr, wb_m2s_dbg_fauxfs_cpu_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_fauxfs_cpu_dat, wb_m2s_dbg_fauxfs_cpu_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_fauxfs_cpu_sel, wb_m2s_dbg_fauxfs_cpu_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_fauxfs_cpu_we, wb_m2s_dbg_fauxfs_cpu_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_fauxfs_cpu_cyc, wb_m2s_dbg_fauxfs_cpu_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_fauxfs_cpu_stb, wb_m2s_dbg_fauxfs_cpu_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_fauxfs_cpu_cti, wb_m2s_dbg_fauxfs_cpu_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_fauxfs_cpu_bte, wb_m2s_dbg_fauxfs_cpu_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_fauxfs_cpu_dat, wb_s2m_dbg_fauxfs_cpu_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_fauxfs_cpu_ack, wb_s2m_dbg_fauxfs_cpu_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_fauxfs_cpu_err, wb_s2m_dbg_fauxfs_cpu_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_fauxfs_cpu_rty, wb_s2m_dbg_fauxfs_cpu_rty}),
    .wbs_adr_o (wb_fauxfs_cpu_adr_o),
    .wbs_dat_o (wb_fauxfs_cpu_dat_o),
    .wbs_sel_o (wb_fauxfs_cpu_sel_o),
    .wbs_we_o  (wb_fauxfs_cpu_we_o),
    .wbs_cyc_o (wb_fauxfs_cpu_cyc_o),
    .wbs_stb_o (wb_fauxfs_cpu_stb_o),
    .wbs_cti_o (wb_fauxfs_cpu_cti_o),
    .wbs_bte_o (wb_fauxfs_cpu_bte_o),
    .wbs_dat_i (wb_fauxfs_cpu_dat_i),
    .wbs_ack_i (wb_fauxfs_cpu_ack_i),
    .wbs_err_i (wb_fauxfs_cpu_err_i),
    .wbs_rty_i (wb_fauxfs_cpu_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_nand_cpu
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_nand_cpu_adr, wb_m2s_dbg_nand_cpu_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_nand_cpu_dat, wb_m2s_dbg_nand_cpu_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_nand_cpu_sel, wb_m2s_dbg_nand_cpu_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_nand_cpu_we, wb_m2s_dbg_nand_cpu_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_nand_cpu_cyc, wb_m2s_dbg_nand_cpu_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_nand_cpu_stb, wb_m2s_dbg_nand_cpu_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_nand_cpu_cti, wb_m2s_dbg_nand_cpu_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_nand_cpu_bte, wb_m2s_dbg_nand_cpu_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_nand_cpu_dat, wb_s2m_dbg_nand_cpu_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_nand_cpu_ack, wb_s2m_dbg_nand_cpu_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_nand_cpu_err, wb_s2m_dbg_nand_cpu_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_nand_cpu_rty, wb_s2m_dbg_nand_cpu_rty}),
    .wbs_adr_o (wb_nand_cpu_adr_o),
    .wbs_dat_o (wb_nand_cpu_dat_o),
    .wbs_sel_o (wb_nand_cpu_sel_o),
    .wbs_we_o  (wb_nand_cpu_we_o),
    .wbs_cyc_o (wb_nand_cpu_cyc_o),
    .wbs_stb_o (wb_nand_cpu_stb_o),
    .wbs_cti_o (wb_nand_cpu_cti_o),
    .wbs_bte_o (wb_nand_cpu_bte_o),
    .wbs_dat_i (wb_nand_cpu_dat_i),
    .wbs_ack_i (wb_nand_cpu_ack_i),
    .wbs_err_i (wb_nand_cpu_err_i),
    .wbs_rty_i (wb_nand_cpu_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_bootrom0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_i_bootrom0_adr, wb_m2s_or1k_d_bootrom0_adr, wb_m2s_dbg_bootrom0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_i_bootrom0_dat, wb_m2s_or1k_d_bootrom0_dat, wb_m2s_dbg_bootrom0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_i_bootrom0_sel, wb_m2s_or1k_d_bootrom0_sel, wb_m2s_dbg_bootrom0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_i_bootrom0_we, wb_m2s_or1k_d_bootrom0_we, wb_m2s_dbg_bootrom0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_i_bootrom0_cyc, wb_m2s_or1k_d_bootrom0_cyc, wb_m2s_dbg_bootrom0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_i_bootrom0_stb, wb_m2s_or1k_d_bootrom0_stb, wb_m2s_dbg_bootrom0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_i_bootrom0_cti, wb_m2s_or1k_d_bootrom0_cti, wb_m2s_dbg_bootrom0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_i_bootrom0_bte, wb_m2s_or1k_d_bootrom0_bte, wb_m2s_dbg_bootrom0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_i_bootrom0_dat, wb_s2m_or1k_d_bootrom0_dat, wb_s2m_dbg_bootrom0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_i_bootrom0_ack, wb_s2m_or1k_d_bootrom0_ack, wb_s2m_dbg_bootrom0_ack}),
    .wbm_err_o ({wb_s2m_or1k_i_bootrom0_err, wb_s2m_or1k_d_bootrom0_err, wb_s2m_dbg_bootrom0_err}),
    .wbm_rty_o ({wb_s2m_or1k_i_bootrom0_rty, wb_s2m_or1k_d_bootrom0_rty, wb_s2m_dbg_bootrom0_rty}),
    .wbs_adr_o (wb_bootrom0_adr_o),
    .wbs_dat_o (wb_bootrom0_dat_o),
    .wbs_sel_o (wb_bootrom0_sel_o),
    .wbs_we_o  (wb_bootrom0_we_o),
    .wbs_cyc_o (wb_bootrom0_cyc_o),
    .wbs_stb_o (wb_bootrom0_stb_o),
    .wbs_cti_o (wb_bootrom0_cti_o),
    .wbs_bte_o (wb_bootrom0_bte_o),
    .wbs_dat_i (wb_bootrom0_dat_i),
    .wbs_ack_i (wb_bootrom0_ack_i),
    .wbs_err_i (wb_bootrom0_err_i),
    .wbs_rty_i (wb_bootrom0_rty_i));

endmodule
